//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTb
    {
        public int invoiceId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public int UserId { get; set; }
        public string PaymentType { get; set; }
        public string Status { get; set; }
        public string CreditCardInfo { get; set; }
    
        public virtual UserTb UserTb { get; set; }
    }
}
