//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTb()
        {
            this.OrderTbs = new HashSet<OrderTb>();
        }
    
        public int Pid { get; set; }
        public string Pname { get; set; }
        public string Pcompany { get; set; }
        public string Pcolor { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Pimage { get; set; }
        public string Pdescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTb> OrderTbs { get; set; }
    }
}
