//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebsite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntity : DbContext
    {
        public DbEntity()
            : base("name=DbEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTb> AdminTbs { get; set; }
        public virtual DbSet<InvoiceTb> InvoiceTbs { get; set; }
        public virtual DbSet<OrderTb> OrderTbs { get; set; }
        public virtual DbSet<ProductTb> ProductTbs { get; set; }
        public virtual DbSet<UserTb> UserTbs { get; set; }
    }
}
