//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTb()
        {
            this.InvoiceTbs = new HashSet<InvoiceTb>();
            this.OrderTbs = new HashSet<OrderTb>();
        }
    
        public int Id { get; set; }
        public string UName { get; set; }
        public string U_mail { get; set; }
        public string U_contact { get; set; }
        public string Uaddress { get; set; }
        public string Ucnic { get; set; }
        public string ZipCode { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTb> InvoiceTbs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTb> OrderTbs { get; set; }
    }
}
