//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyBook_Store_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class AdminTb
    {
        public int Id { get; set; }

        public string Name { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "***")]
        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "***")]
        public string Password { get; set; }
    }
}
