//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyBook_Store_Management_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class CustomerTb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerTb()
        {
            this.InvoiceTbs = new HashSet<InvoiceTb>();
        }

        public int CId { get; set; }
        public string CName { get; set; }
        public string CPhoneNo { get; set; }
        public Nullable<decimal> CDue { get; set; }
        public Nullable<int> User { get; set; }

        public virtual UserTb UserTb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceTb> InvoiceTbs { get; set; }
    }
}
