//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyBook_Store_Management_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class InventoryTb
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public Nullable<int> PQuantity { get; set; }
        public Nullable<decimal> PPrice { get; set; }
        public Nullable<int> User { get; set; }

        public virtual UserTb UserTb { get; set; }
    }
}
