//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallyBook_Store_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTb> AdminTbs { get; set; }
        public virtual DbSet<CustomerTb> CustomerTbs { get; set; }
        public virtual DbSet<InventoryTb> InventoryTbs { get; set; }
        public virtual DbSet<InvoiceTb> InvoiceTbs { get; set; }
        public virtual DbSet<SupInvoiceTb> SupInvoiceTbs { get; set; }
        public virtual DbSet<SupplierTb> SupplierTbs { get; set; }
        public virtual DbSet<UserTb> UserTbs { get; set; }
    }
}
